
# ------------------------------------------------------------------------------
# YAML Configuration for DUT (Device Under Test) Connections
# 
# This file defines the connection settings for different DUTs, including
# the communication interface (e.g., UART or socket), baud rate, power 
# switch configuration, and IP address for power control.
# 
# Fields:
# - name:              Unique identifier for the DUT
# - url:               Connection URL for the DUT (can be a serial device or a socket)
# - baudrate:          Communication speed (baud rate) for the serial connection
# - power_switch_port: Port on the power switch that controls the DUT's power
# - power_port_IP:     IP address of the power switch controlling the DUT
# 
# Example Entries:
# - name: "dutEth"
#   url: "socket://130.246.241.133:20108"
#   baudrate: 115200
#   power_switch_port: 8
#   power_port_IP: '130.246.241.130'
#
# - name: "dutUART"
#   url: "/dev/ttyUSB0"
#   timeout: 5
#   baudrate: 115200
#   power_switch_port: 7
#   power_port_IP: '192.168.0.216'
# ------------------------------------------------------------------------------

- name: "aaaaa"
  url: "socket://192.168.0.104:20108"
  timeout: 4
  baudrate: 115200
  power_switch_port: 9
  power_port_IP: '192.168.0.216'


