# config.yaml
# see PySerial URL handlers for specifying the URL
# https://pyserial.readthedocs.io/en/latest/url_handlers.html

- name: "dutUART"
  url: "/dev/ttyACM0"
  baudrate: 115200
  power_switch_port: 1
  power_port_IP: '0.0.0.0'

# - name: "dutIP"
#   url: "socket://192.168.2.16:20108"
#   baudrate: 115200
#   power_switch_port: 2
#   power_port_IP: '0.0.0.0'

