CLIENT_SERIAL_FRAME_ERROR = 1
CLIENT_SERIAL_BUFFER_OVERFLOW = 1

CLIENT_SERIAL_TIMEOUT = 19
CLIENT_SERIAL_FRAME_RX = 20
CLIENT_REST_OCP = 21
CLIENT_RESET_LDO = 22
CLIENT_REFLASH = 23
CLIENT_ERROR = 24
CLIENT_FLASH_TIMEOUT = 25
SERVER_POWERCYCLE_RPI = 26
SERVER_POWERCYCLE_RPI_FAILED = 27
