# config.toml

number_conected_uarts = 2

[[uart]]
name = "dut0"
tty = "/dev/ttyDUT0"
baudrate=115200
index = 0
power_port_IP = '0.0.0.0'

[[uart]]
name = "dut1"
tty = "/dev/ttyDUT1"
baudrate=115200
index = 0
power_port_IP = '0.0.0.0'

[[uart]]
name = "uart1"
tty = "/dev/ttyDUT1"
baudrate=115200
index = 0
power_port_IP = '0.0.0.0'

#scp -r username@rpi_ip_address:/path/to/folder /path/on/host
